spring:
  application:
    name: "api-gateway"
  cloud:
    gateway:
      mvc:
        routes:
          - id : booking-service
            uri: lb://booking-service
            predicates:
              - Path=/api/bookings
          - id: event-service
            uri: lb://event-service
            predicates:
              - Path=/api/events
          - id: payment-service
            uri: lb://payment-service
            predicates:
              - Path=/api/payment
          - id: discovery-server
            uri: http://localhost:8761
            predicates:
              - Path=/eureka/web
            filters:
              - setPath=/
          - id: discovery-server-static
            uri: http://localhost:8761
            predicates:
              - Path=/eureka/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway: trace
          route:
              RouteDefinitionLocator: info
server:
  port: 8080
