spring:
  application:
    name: "api-gateway"
  cloud:
    gateway:
      mvc:
        routes:
          - id : booking-service
            uri: lb://booking-service
            predicates:
              - Path=/api/bookings

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway: trace
          route:
              RouteDefinitionLocator: info

