spring:
  application:
    name: "payment-service"
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    username: admin
    password:
    url: jdbc:h2:file:~/payment
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notification
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping:event: com.eventbooking.paymentservice.event.PaymentEvent

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8083
